Allow messages to be sent using the non-persistent delivery mode
Particular/NServiceBus.RabbitMQ pull request #685
Opened 2020-10-12 14:39 UTC by andreasohlund

2020-10-12 15:46 UTC, ramonsmits requested changes
Removal of ToStrings and string literals.

2020-10-12 15:46 UTC, ramonsmits commented on src/NServiceBus.Transport.RabbitMQ.Tests/When_sending_a_message_over_rabbitmq.cs
> +            return Verify(new OutgoingMessageBuilder(), result => Assert.True(result.Headers[Headers.NonDurableMessage] == "False"));
```suggestion
            return Verify(new OutgoingMessageBuilder(), result => Assert.True(result.Headers[Headers.NonDurableMessage] == bool.FalseString));
```

2020-10-12 15:46 UTC, ramonsmits commented on src/NServiceBus.Transport.RabbitMQ/Configuration/RabbitMQTransportOptionsExtensions.cs
> +            options.SetHeader(BasicPropertiesExtensions.UseNonPersistentDeliveryHeader,true.ToString());
```suggestion
            options.SetHeader(BasicPropertiesExtensions.UseNonPersistentDeliveryHeader, bool.TrueString);
```

2020-10-12 15:46 UTC, ramonsmits commented on src/NServiceBus.Transport.RabbitMQ/Configuration/RabbitMQTransportOptionsExtensions.cs
> +            options.SetHeader(BasicPropertiesExtensions.UseNonPersistentDeliveryHeader, true.ToString());
```suggestion
            options.SetHeader(BasicPropertiesExtensions.UseNonPersistentDeliveryHeader, bool.TrueString);
```

2020-10-12 15:46 UTC, ramonsmits commented on src/NServiceBus.Transport.RabbitMQ/Configuration/RabbitMQTransportOptionsExtensions.cs
> +            options.SetHeader(BasicPropertiesExtensions.UseNonPersistentDeliveryHeader, true.ToString());
```suggestion
            options.SetHeader(BasicPropertiesExtensions.UseNonPersistentDeliveryHeader, bool.TrueString);
```

2020-10-13 12:19 UTC, andreasohlund commented
I will wrap this up once https://github.com/Particular/NServiceBus/pull/5785 is merged and we have a core alpha to compile against

2020-10-15 15:03 UTC, lailabougria approved these changes

2020-10-16 07:22 UTC, merged

2020-10-16 15:16 UTC, andreasohlund commented on src/NServiceBus.Transport.RabbitMQ.Tests/When_sending_a_message_over_rabbitmq.cs
> +                Assert.True(message.Headers.ContainsKey(BasicPropertiesExtensions.UseNonPersistentDeliveryHeader), "Temp header should not removed to make sure that retries keeps the setting");
The reasoning is that by keeping the header retries will not loose this setting, eg doing retries via SC. Does that make sense?